--VOTOS

INSERT INTO VOTOS(NOMBRE_ARTISTA, FAVORITOS) VALUES ( 'Aitana', 25);
INSERT INTO VOTOS(NOMBRE_ARTISTA, FAVORITOS) VALUES ('Ana Mena', 8);
INSERT INTO VOTOS(NOMBRE_ARTISTA, FAVORITOS) VALUES ('Camilo',1 );
INSERT INTO VOTOS(NOMBRE_ARTISTA, FAVORITOS) VALUES ('C. Tangana',13 );
INSERT INTO VOTOS(NOMBRE_ARTISTA, FAVORITOS) VALUES ('Dani Fernández', 2);
INSERT INTO VOTOS(NOMBRE_ARTISTA, FAVORITOS) VALUES ('Dvicio',9 );
INSERT INTO VOTOS(NOMBRE_ARTISTA, FAVORITOS) VALUES ('Funzo & Baby Loud', 12);
INSERT INTO VOTOS(NOMBRE_ARTISTA, FAVORITOS) VALUES ('Hens',12 );
INSERT INTO VOTOS(NOMBRE_ARTISTA, FAVORITOS) VALUES ('Lola Indigo', 14);
INSERT INTO VOTOS(NOMBRE_ARTISTA, FAVORITOS) VALUES ('Luis Fonsi',3 );
INSERT INTO VOTOS(NOMBRE_ARTISTA, FAVORITOS) VALUES ('Marlon', 12);
INSERT INTO VOTOS(NOMBRE_ARTISTA, FAVORITOS) VALUES ('Maria Becerra', 5);
INSERT INTO VOTOS(NOMBRE_ARTISTA, FAVORITOS) VALUES ('Marmi',8 );
INSERT INTO VOTOS(NOMBRE_ARTISTA, FAVORITOS) VALUES ('Nil Moliner', 5);
INSERT INTO VOTOS(NOMBRE_ARTISTA, FAVORITOS) VALUES ('Pole', 19);
INSERT INTO VOTOS(NOMBRE_ARTISTA, FAVORITOS) VALUES ('Rosalia',11 );
INSERT INTO VOTOS(NOMBRE_ARTISTA, FAVORITOS) VALUES ('Sebastián Yatra',6 );
INSERT INTO VOTOS(NOMBRE_ARTISTA, FAVORITOS) VALUES ('Taburete',17 );
INSERT INTO VOTOS(NOMBRE_ARTISTA, FAVORITOS) VALUES ('Tini', 15);
INSERT INTO VOTOS(NOMBRE_ARTISTA, FAVORITOS) VALUES ('Zzoilo', 12);


--CANCIONES

INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('En El Coche', 1, 'En El Coche');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Formentera', 1, 'Formentera');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Berlin', 1, 'Berlin');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Musica Ligera', 2, 'Musica Ligera');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Un beso de improvisto', 2, 'A Un Paso De La Luna');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('A Un Paso De La Luna', 2, 'A Un Paso De La Luna');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Millones', 3, 'Mis Manos');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('KESI', 3, 'KESI');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Pesadilla', 3, 'Pesadilla');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Demasiadas Mujeres', 4, 'El Madrileño');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Ateo', 4, 'Ateo');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Mala Mujer', 4, 'Mala Mujer');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Disparos', 5, 'Incendios');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Y te diré', 5, 'Incendios');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Frio', 5, 'Frio');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Sobrenatural', 6, 'Impulso');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Casi Humanos', 6, 'Que Tienes Tu');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Paraiso', 6, 'Justo Ahora');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Inmortales', 7, 'Inmortales');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('El poema', 7, 'Inmortales');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Luces de neon', 7, 'Inmortales');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Hensito', 8, 'Hensito');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Me encantas', 8, 'Hensito');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Tu Historia Y La Mia', 8, 'Tu Historia Y La Mia');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('La Niña De La Escuela', 9, 'La Niña');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Toy Story', 9, 'Toy Story');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Mujer Bruja', 9, 'Akelarre');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Despacito', 10, 'Vida');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Tanto', 10, 'Aire');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Besame', 10, 'Besame');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Mi Macarena', 11, 'Cosas Que No Se Pagan Con Dinero');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Contigo', 11, 'Cosas Que No Se Pagan Con Dinero');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('De Perreo', 11, 'De Perreo');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Animal', 12, 'Animal');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Cerquita de Ti', 12, 'Animal');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Acaramelao', 12, 'Animal');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Divina', 13, 'Divina');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Tu Foto Del DNI', 13, 'Tu Foto Del DNI');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Soy Un Chulo', 13, 'Soy Un Chulo');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Libertad', 14, 'Un Secreto Al Que Gritar');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Polvora', 14, 'Un Secreto Al Que Gritar');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Bailando', 14, 'Bailando Rn la Batalla');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Batmovil Remix', 15, 'Batmovil Remix');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Amor De Verbena', 15, 'Tutto Bene');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Dale', 15, 'Dale');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Malamente', 16, 'El Mal Querer');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Motomami', 16, 'Motomami');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Saoko', 16, 'Motomami');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Basicamente', 17, 'Dharma');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Tacones Rojos', 17, 'Dharma');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Un Año', 17, 'Fantasia');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Sirenas', 18, 'Dr Charas');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Madame Ayahuasca', 18, 'Madame Ayahuasca');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Belerofón', 18, 'Madame Ayahuasca');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Mienteme', 19, 'Mienteme');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Bar', 19, 'Bar');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('La Triple T', 19, 'La Triple T');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Superman', 20, 'Superman');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Mon Amour', 20, 'Mon Amour');
INSERT INTO CANCIONES(NOMBRE_CANCION, ARTISTA_ID, ALBUM) VALUES ('Menta', 20, 'Menta');

--USUARIOS

INSERT INTO USUARIOS(NOMBRE, APELLIDOS, EDAD, EMAIL, TELEFONO) VALUES ('Eva', 'Manrique Sanz', 20, 'eva.manriquesz@gmail.com', 630720672);


--PRODUCTOS

INSERT INTO PRODUCTOS(NOMBRE, PRECIO, EXISTENCIAS) VALUES ('Sudadera Coca Cola Roja', 40, 37);
INSERT INTO PRODUCTOS(NOMBRE, PRECIO, EXISTENCIAS) VALUES ('Sudadera Coca Cola Blanca', 40, 26);
INSERT INTO PRODUCTOS(NOMBRE, PRECIO, EXISTENCIAS) VALUES ('Libreta Coca Cola', 15, 68);
INSERT INTO PRODUCTOS(NOMBRE, PRECIO, EXISTENCIAS) VALUES ('Tote Bag Coca Cola', 20, 57);
INSERT INTO PRODUCTOS(NOMBRE, PRECIO, EXISTENCIAS) VALUES ('Pijama Coca Cola', 35, 27);
INSERT INTO PRODUCTOS(NOMBRE, PRECIO, EXISTENCIAS) VALUES ('Calcetines Coca Cola', 10, 85);


--JUGADORES

INSERT INTO JUGADORES(NOMBRE, APELLIDOS, EDAD, GENERO, EMAIL, NIVEL, ACIERTOS) VALUES ('Sofia', 'Barquero', 22, 'Mujer', 'sofia@gmail.com', 'Facil', 5)




