DROP TABLE IF EXISTS STOCK;

CREATE TABLE "STOCK" (
    "IDENTIFICADOR"  IDENTITY  NOT NULL PRIMARY KEY,
    "MODELO" VARCHAR2(40) NOT NULL,
    "COLOR" VARCHAR2(40) NOT NULL,
    "EXISTENCIAS" NUMBER NOT NULL
    );

DROP TABLE IF EXISTS VOTOS;

CREATE TABLE "VOTOS" (
   "ARTISTA_ID" IDENTITY NOT NULL PRIMARY KEY,
   "NOMBRE_ARTISTA" VARCHAR2(50) NOT NULL,
   "FAVORITOS" NUMBER NOT NULL
);

